Vagrant.configure('2') do |config|

  config.ssh.username = 'vagrant'

  config.vm.provider :openstack do |os, ov|
    os.server_name                      = 'vagrant_test'
    os.openstack_auth_url               = 'https://openstack2-corp.cerner.com:5000/v3'
    os.identity_api_version             = '3'
    os.project_name                     = 'OpAdDev-corp'
    os.project_domain_name              = 'northamerica.cerner.net'
    os.user_domain_name                 = 'northamerica.cerner.net'
    os.username                         = 'NL048740'
    os.password                         = 'Coffee1277!'
    os.region                           = 'nova'

    os.floating_ip_pool                 = '	corp_dvport_az3_nat'

    os.flavor                           = 'm4.small.v2'
    os.image                            = 'oracle-7-x86_64-current-disa-2019_28_1562861717'
    os.networks                        << 'OpAdDev-corp-private-kc-corp-8-a-network'
    ov.nfs.functional = false
  end
end
