Vagrant.configure("2") do |config|

  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.network "private_network", ip: "10.10.10.10",
      virtualbox__intnet: true
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/trusty64"
    slave.vm.network "private_network", ip: "10.10.10.20",
      virtualbox__intnet: true
  end

end
