Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
      master.vm.box = "ubuntu/xenial64"
      master.vm.network "private_network", ip: "10.0.0.10", virtualbox__intnet: true
      master.vm.provider "virtualbox" do |v|
        v.memory = 512
      end
      master.vm.provision "shell", inline: "cp /vagrant/* $HOME"
      master.vm.provision "ansible_local" do |ansible|
        ansible.install_mode = "default"
        ansible.playbook = "bootstrap.yml"
        ansible.config_file = "ansible.cfg"
      end
    end

    config.vm.define "slave" do |slave|
      slave.vm.box = "ubuntu/xenial64"
      slave.vm.network "private_network", ip: "10.0.0.20", virtualbox__intnet: true
      slave.vm.provider "virtualbox" do |v|
        v.memory = 512
      end
    end

end
