# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.base_mac = "0800276CEEAA"

  config.vm.define "n9kv1" do |n9kv1|

        n9kv1.vm.box = "nxos-test"

        n9kv1.ssh.insert_key = false

        n9kv1.vm.boot_timeout = 420

        n9kv1.vm.synced_folder '.', '/vagrant', disabled: true

        n9kv1.vm.network "private_network", ip: "192.168.1.2", auto_config: false, virtualbox__intnet: "nxosv_network1"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network2"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network3"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network4"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network5"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network6"

        n9kv1.vm.network "private_network", auto_config: false, virtualbox__intnet: "nxosv_network7"

        n9kv1.vm.provider :virtualbox do |vb|
                #vb.memory = 5000

                #vb.cpus = 2

                vb.customize ['modifyvm',:id,'--uartmode1','server','\\\\.\pipe\COM1']

                vb.customize ['modifyvm',:id,'--nicpromisc2','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc3','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc4','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc5','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc6','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc7','allow-all']

                vb.customize ['modifyvm',:id,'--nicpromisc8','allow-all']

                vb.customize "pre-boot", [

                        "storageattach", :id,



                        "--storagectl", "SATA",

                        "--port", "1",

                        "--device", "0",

                        "--type", "dvddrive",

                        "--medium", "./nxosv_config.iso",

                ]
        end

  end

end
