# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.base_mac = "0800276CEEAA"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.network :forwarded_port, guest: 8081, host: 5555
  config.vm.provision "docker" do |docker|
    docker.run "hello-world"
  end
end
